package mapperGenerator;

import java.util.Date;

public class businessCheck {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_check.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_check.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_check.business_id
     *
     * @mbggenerated
     */
    private String businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_check.business_type
     *
     * @mbggenerated
     */
    private Byte businessType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_check.created
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_check.created_user
     *
     * @mbggenerated
     */
    private String createdUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_check.modified
     *
     * @mbggenerated
     */
    private Date modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_check.modified_user
     *
     * @mbggenerated
     */
    private String modifiedUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_check.yn
     *
     * @mbggenerated
     */
    private Byte yn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_check.id
     *
     * @return the value of business_check.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_check.id
     *
     * @param id the value for business_check.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_check.uuid
     *
     * @return the value of business_check.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_check.uuid
     *
     * @param uuid the value for business_check.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_check.business_id
     *
     * @return the value of business_check.business_id
     *
     * @mbggenerated
     */
    public String getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_check.business_id
     *
     * @param businessId the value for business_check.business_id
     *
     * @mbggenerated
     */
    public void setBusinessId(String businessId) {
        this.businessId = businessId == null ? null : businessId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_check.business_type
     *
     * @return the value of business_check.business_type
     *
     * @mbggenerated
     */
    public Byte getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_check.business_type
     *
     * @param businessType the value for business_check.business_type
     *
     * @mbggenerated
     */
    public void setBusinessType(Byte businessType) {
        this.businessType = businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_check.created
     *
     * @return the value of business_check.created
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_check.created
     *
     * @param created the value for business_check.created
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_check.created_user
     *
     * @return the value of business_check.created_user
     *
     * @mbggenerated
     */
    public String getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_check.created_user
     *
     * @param createdUser the value for business_check.created_user
     *
     * @mbggenerated
     */
    public void setCreatedUser(String createdUser) {
        this.createdUser = createdUser == null ? null : createdUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_check.modified
     *
     * @return the value of business_check.modified
     *
     * @mbggenerated
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_check.modified
     *
     * @param modified the value for business_check.modified
     *
     * @mbggenerated
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_check.modified_user
     *
     * @return the value of business_check.modified_user
     *
     * @mbggenerated
     */
    public String getModifiedUser() {
        return modifiedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_check.modified_user
     *
     * @param modifiedUser the value for business_check.modified_user
     *
     * @mbggenerated
     */
    public void setModifiedUser(String modifiedUser) {
        this.modifiedUser = modifiedUser == null ? null : modifiedUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_check.yn
     *
     * @return the value of business_check.yn
     *
     * @mbggenerated
     */
    public Byte getYn() {
        return yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_check.yn
     *
     * @param yn the value for business_check.yn
     *
     * @mbggenerated
     */
    public void setYn(Byte yn) {
        this.yn = yn;
    }
}