package mapperGenerator;

import java.util.List;
import mapperGenerator.businessCheck;
import mapperGenerator.businessCheckExample;
import org.apache.ibatis.annotations.Param;

public interface businessCheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_check
     *
     * @mbggenerated
     */
    int countByExample(businessCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_check
     *
     * @mbggenerated
     */
    int deleteByExample(businessCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_check
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_check
     *
     * @mbggenerated
     */
    int insert(businessCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_check
     *
     * @mbggenerated
     */
    int insertSelective(businessCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_check
     *
     * @mbggenerated
     */
    List<businessCheck> selectByExample(businessCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_check
     *
     * @mbggenerated
     */
    businessCheck selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_check
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") businessCheck record, @Param("example") businessCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_check
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") businessCheck record, @Param("example") businessCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_check
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(businessCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_check
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(businessCheck record);
}